# Framework for running automated tests on Open Source Brain using Travis-CI.
# See https://github.com/OpenSourceBrain/osb-model-validation for more details

dist: trusty
sudo: false

addons:
  apt:
    packages:
       # Requirements for Neuron/OMV/etc
    - python-numpy 
    - python-scipy 
    - python-tornado
    - python-matplotlib 
    - python-tk

language: python
python:
     - "2.7"

virtualenv:
    system_site_packages: true 

env:
     - OMV_ENGINE=jNeuroML
     - OMV_ENGINE=jNeuroML_NEURON
     - OMV_ENGINE=jNeuroML_validatev1
     - OMV_ENGINE=jNeuroML_validate
     - OMV_ENGINE=NON_OMV_TESTS
     

before_install:
    # To run tests requiring a graphical user interface on Travis CI, use xvfb (X Virtual Framebuffer) to imitate a display.
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
    # Required to run OMV tests
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install tornado

script:
    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests"
    - if [[ ${OMV_ENGINE} == "NON_OMV_TESTS" ]]; then echo "Continuing with tests not under OMV..."; else exit $OMV_SUCCESS; fi
    - echo "Running non OMV tests..."
    - python setup.py install

    # Test readers
    - cd CElegans/pythonScripts

    # Install PyOpenWorm
    - git clone https://github.com/openworm/PyOpenWorm.git
    - cd PyOpenWorm
    - git checkout 7ff1266  # As used in Docker for OpenWorm
    - python setup.py install
    - cd ..

    # Testing RegenerateConnectome.py, SpreadsheetDataReader.py, OpenWormReader.py via py.test
    # 
    # 
    #        NOTE: disabling this test until issue with install of PyOpenWorm is resolved: 
    #        https://travis-ci.org/openworm/CElegansNeuroML/jobs/268419603
    # - py.test -vs python_script_tester.py
    # 
    ###############################################
    
    # Testing c302
    - cd c302 
    - python c302_IClamp.py A    
    - omv install NEURON # Need to install NEURON
    - export NEURON_HOME=/home/travis/neuron/nrn/x86_64/
    #- python runAndPlot.py -test     # Works in https://github.com/openworm/c302
    #- python c302_utils.py -nogui    # Works in https://github.com/openworm/c302

